IMAGE_FORMAT = '.jpg'

FACE_COMPARISON_TOLERANCE = 0.6
TESTING_IMAGE = 'test_faces/unknown.jpg'
BBOX_TEXT_SIZE = 100
BBOX_TEXT_FILL = 'red'
BBOX_WIDTH = 2
BBOX_FILL = 'red'

WEBCAM_FRAME_RESIZE = 500
VJ_MIN_NEIGHBORS = 5
VJ_FACE_MIN_SIZE = (30, 30)
VJ_SCALE_FACTOR = 1.1

CV2_FONT_SCALE = 0.75
CV2_TEXT_FILL = (0, 0, 255)
CV2_BBOX_FILL = (0, 0, 255)

WEBCAM_SOURCE = 0

FACE_DETECTOR_NUMBER_TIMES_UPSAMPLE = 1
FACE_DETECTOR_MODEL = 'hog'
